name: Terraform Validation

on:
  pull_request:
    branches: [ main ]

jobs:
  build:
    name: terraform-validation

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_DEFAULT_REGION }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@main
        with:
          version: '1.4.2'

      - name: Terraform fmt
        run: terraform fmt -check 

      - name: Terraform init
        run: terraform init 

      - name: Terraform validate
        run: terraform validate 